#include <iostream>
#include <cstdlib>
#include <ctime>

using namespace std;

/*
Code by Michael Yan 9/29/19 (v2 9/23/19)

This code (v3) runs a simple guessing game, where the user must guess a number between 0 and 100 (including
0 and 100). It will keep track of the amount of guesses the user took to corretly guess the random number
generated by the code. It will also give the user a hint of the number by telling them if their guess was
too low or too high.
 */



//main function
int main()
{

  //defining necessary variables
  int isPlaying = 1;
  int guesses = 0;
  int newNumber = 1;

  //dialogue
  cout << "Hello! Welcome to the guessing game." <<endl;
  cout << "I will now choose a number between (and including) 0 and 100." <<endl;


  while(newNumber = 1){ //first while loop to govern whether or not a seed is used for random number

    srand(time(NULL)); //sets new seed
    int randomNumber = (rand() % 101); //generates numbers between 0 and 100 including
    
    while(isPlaying = 1) //second while loop for if the user still wants to play
    {
   
  cout << "Guess the number: ";
  int userguess;
  cin >> userguess; //take user input for their guess
  cout << "You guessed ";
  cout << userguess;
  cout << ". ";

  //was used for debugging
  /*cout << "The number was ";
  cout << randomNumber;
  cout << ". " << endl;*/

  if(userguess == randomNumber) //if guess is correct
  {
    cout << "You guessed correctly!" << endl;
    cout << "It took you ";
    cout << guesses; //print out number of guesses to guess correctly
    cout<< " tries to guess the number corretly. Nice job!" << endl;
    cout << "Would you like to play again? y/n" << endl;
    char yesNo;
    cin >> yesNo; //user input for if user would like to play again
    if(yesNo == 'y') {
      cout << "You said yes." << endl;
      guesses = 0;
      srand(time(NULL));
      int randomNumber = (rand() % 101);
      break; //break out of second while loop to generate a new number
    }
    else if (yesNo == 'n') {
      cout << "Thanks for playing." <<endl;
      return(0); //exit program
    }
  }
  else{
    if(userguess > randomNumber){
      cout << "Your guess is too high." <<endl;
      guesses += 1; //anytime the guess is incorrect, add a guess to the number of guesses
    }
    else if(userguess < randomNumber){
      cout << "Your guess is too low." <<endl;
      guesses +=1; //same
    }

  }
  }

 }
  
}
